### ISSUE TITLE
Error when creating a note

### ISSUE THREAD

**Issue by jordanbrock** [joeworkman/paperless#1]
Howdy,

I have paperless "mostly" setup. 

The --simulate command works fine, but then I get the following error when running "paperless create itinerary.pdf"

Processing rules...
Processing PDF pages...
Basing the date off the discovered string (2): 5August 2011
Saving /Users/jordanbrock/Dropbox/Action/itinerary.pdf to
- ---------------------------------------------
- File: /Users/jordanbrock/Dropbox/Action/itinerary.pdf
- Service: finder
- Destination: /Users/jordanbrock/Dropbox/Documents/Processed
- Title: itinerary.pdf
- Date: 2011-08-05
- Tags:
- ---------------------------------------------

There was an error processing the command.
error: undefined method `+' for nil:NilClass

I _suspect_ that the error is occurring in lib/paperless/services/finder.rb between lines 24:29, but I haven't been able to confirm that. I can't work out what would be nil, because the output seems to have all the fields it needs.

Is there any way to run it in "verbose" mode, or a debug mode?

PS Thanks for a (what I hope will be) a fantastic service that pretty much fits my needs exactly.

**Comment by jordanbrock** [comment]
FYI I'm using rbenv and ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin12.2.1]

**Comment by steverinn** [comment]
Same error as Jordan.  I'm using rvm and ruby-1.9.3-p392.  I got a _little_ farther.  Adding a title to my rule:

```
title: '<match>-<date>'
```

got me a little farther.  I'm no longing getting the undefined method error.  But now I get an error:

```
There was an error processing the command. 
error: no such option: force
```

Looking at line 31 of finder.rb, I don't see that FileUtils.cp supports the :force option, so I'm not sure what is supposed to be going on there.

I heartily second the thanks--I'm thinking this is going to be a great companion to hazel and a new ScanSnap.

**Comment by jordanbrock** [comment]
I added the 

```
title: '<match>-<date>'
```

line to my rule and got the same error as @steverinn

**Comment by joeworkman** [comment]
Thanks for the feedback Jordan. Sorry that I did not respond to your comment on my blog yet. I will have a look at your bug report within a couple of days. I am trying to get an update submitted to MAS by Friday. I will respond here again. Please keep the feedback coming!

**Comment by jordanbrock** [comment]
No worries Joe. Whenever you get the time. I'll keep trying to work out 
what's going on.

Joe Workman wrote:

**Comment by joeworkman** [comment]
Could you send me the rules file that caused this? I did a few simple tests and was not able to replicate it. I am working on v0.2 right now...

**Comment by jordanbrock** [comment]
Here's my .paperless-rc

```
---
:ocr_engine: pdfpen
:text_ext: txt md mmd
:rules:
:rules_file:
:service: finder
:date_format: ! '%Y-%m-%d'
:date_locale: euro
:date_default: filedate
:destination: /Users/jordanbrock/Dropbox/Documents/Processed
:version: false
:simulate: false
:help: false
commands:
  :_doc: {}
  :editconfig: {}
  :assign: {}
  :create: {}
  :search: {}
  :unassign: {}
:rules:
 -
   description: Date Rule
   scope: content
   condition: <date>
   title: '<date>-<match>'
 -
   description: Find Tamarabuchi
   scope: content filename
   condition: Tamarabuchi
   tags: spintech tamarabuchi
   destination: /Users/jordanbrock/Dropbox/Documents/Spin\ Technologies/Spin\ Documents/Processed
```

**Comment by steverinn** [comment]
And here's mine:

```
---
:ocr_engine: acrobat
:text_ext: txt md mmd
:rules:
-
  description: 'Rule #1 - SearchTest'
  scope: content
  condition: SearchTest
  destination: /Users/steve/Documents/searchtest
  service: finder
  tags: searchtest
  title: '<match>-<date>'
:rules_file: 
:service: finder
:date_format: ! '%Y-%m-%d'
:date_locale: us
:date_default: filedate
:destination: /Users/steve/Documents/inbox
:version: false
:simulate: false
:help: false
commands:
  :_doc: {}
  :editconfig: {}
  :assign: {}
  :create: {}
  :search: {}
  :unassign: {}
```

This was the result of a lot of different changes, so I'm not sure what it looked like when I _first_ got the error.  Again, though, look at the :force option on line 31 of finder.rb.  I was going to try that out and send you a patch, but I've been really busy myself and haven't had time.  Sorry.

**Comment by joeworkman** [comment]
@steverinn Acrobat is not a supported OCR Engine yet.

**Comment by joeworkman** [comment]
I nailed this particular bug. I will release the updated version shortly

**Comment by jordanbrock** [comment]
Awesome. Works great now. Thanks so much.

**Comment by steverinn** [comment]
Same here, once I RTFM and discovered the config file had changed names.  Thanks for fixing that, Joe.

**Comment by joeworkman** [comment]
You may want to join the new user group if you haven't already... https://app.glassboard.com/web/invitation/code/akkmo
